const bookResultFromApi = [
	{
		isbn: "1",
		title: "Lorem ipsum dolor sit amet.",
		author: "Lorem, ipsum dolor.",
		publisher: "Lorem ipsum dolor sit amet.",
		publicationYear: "2024",
		imageUrl: "img",
		libCode: ["12345", "67890"],
	},
	{
		isbn: "2",
		title: "Lorem ipsum dolor sit amet.",
		author: "Lorem, ipsum dolor.",
		publisher: "Lorem ipsum dolor sit amet.",
		publicationYear: "2024",
		imageUrl: "img",
		libCode: ["12345", "67890"],
	},
	{
		isbn: "3",
		title: "Lorem ipsum dolor sit amet.",
		author: "Lorem, ipsum dolor.",
		publisher: "Lorem ipsum dolor sit amet.",
		publicationYear: "2024",
		imageUrl: "img",
		libCode: ["12345", "67890"],
	},
	{
		isbn: "3",
		title: "Lorem ipsum dolor sit amet.",
		author: "Lorem, ipsum dolor.",
		publisher: "Lorem ipsum dolor sit amet.",
		publicationYear: "2024",
		imageUrl: "img",
		libCode: ["12345", "67890"],
	},
	{
		isbn: "3",
		title: "Lorem ipsum dolor sit amet.",
		author: "Lorem, ipsum dolor.",
		publisher: "Lorem ipsum dolor sit amet.",
		publicationYear: "2024",
		imageUrl: "img",
		libCode: ["12345", "67890"],
	},
	{
		isbn: "3",
		title: "Lorem ipsum dolor sit amet.",
		author: "Lorem, ipsum dolor.",
		publisher: "Lorem ipsum dolor sit amet.",
		publicationYear: "2024",
		imageUrl: "img",
		libCode: ["12345", "67890"],
	},
	{
		isbn: "3",
		title: "Lorem ipsum dolor sit amet.",
		author: "Lorem, ipsum dolor.",
		publisher: "Lorem ipsum dolor sit amet.",
		publicationYear: "2024",
		imageUrl: "img",
		libCode: ["12345", "67890"],
	},
	{
		isbn: "3",
		title: "Lorem ipsum dolor sit amet.",
		author: "Lorem, ipsum dolor.",
		publisher: "Lorem ipsum dolor sit amet.",
		publicationYear: "2024",
		imageUrl: "img",
		libCode: ["12345", "67890"],
	},
	{
		isbn: "3",
		title: "Lorem ipsum dolor sit amet.",
		author: "Lorem, ipsum dolor.",
		publisher: "Lorem ipsum dolor sit amet.",
		publicationYear: "2024",
		imageUrl: "img",
		libCode: ["12345", "67890"],
	},
	{
		isbn: "3",
		title: "Lorem ipsum dolor sit amet.",
		author: "Lorem, ipsum dolor.",
		publisher: "Lorem ipsum dolor sit amet.",
		publicationYear: "2024",
		imageUrl: "img",
		libCode: ["12345", "67890"],
	},
	{
		isbn: "3",
		title: "Lorem ipsum dolor sit amet.",
		author: "Lorem, ipsum dolor.",
		publisher: "Lorem ipsum dolor sit amet.",
		publicationYear: "2024",
		imageUrl: "img",
		libCode: ["12345", "67890"],
	},
];

export default bookResultFromApi;
